export ZDOTDIR="$HOME/.config/zsh"

# XDG base directories
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

# Add XDG standard bin dir to PATH
PATH=$PATH:$HOME/.local/bin

export EDITOR=vim
export VISUAL=vscw # Should be in XDG bin
export MANPAGER="sh -c 'col -bx | bat -l man -p'"

eval "$(/opt/homebrew/bin/brew shellenv)"
