#zmodload zsh/zprof
## Set emacs mode
bindkey -e

## Environment variables
ZSH_CONF_DIR="${ZDOTDIR:-$HOME/.config/zsh}/conf.d"

if [[ -d $ZSH_CONF_DIR ]]; then
  # Use a glob that follows symlinks and sorts lexicographically
  # *.zsh files only; nullglob prevents errors if no match
  for conf_file in $(print -rl -- "$ZSH_CONF_DIR"/*.{z,}sh(N) | sort); do 
    [[ -r $conf_file ]] && source "$conf_file"
  done
fi
unset conf_file ZSH_CONF_DIR

## Antidote Init
source $(brew --prefix)/opt/antidote/share/antidote/antidote.zsh
antidote load

## Load functions
ZSH_FUNCTIONS_DIR="${ZDOTDIR:-$HOME/.config/zsh}/functions"

# Add function dir to fpath
[[ -d $ZSH_FUNCTIONS_DIR ]] && fpath=($ZSH_FUNCTIONS_DIR $fpath)

# Autoload all functions in the directory (lazy)
# (:t) strips the path, giving Zsh just the function names
for func_file in "$ZSH_FUNCTIONS_DIR"/*(.N) "$ZSH_FUNCTIONS_DIR"/*(@N); do
  autoload -Uz "${func_file:t}"
done
unset func_file ZSH_FUNCTIONS_DIR

## Init Standalones
source <(fzf --zsh)

## Aliases & Functions
source $ZDOTDIR/aliases.zsh

# ## Prompt
# To customize prompt, run `p10k configure` or edit ~/.config/zsh/.p10k.zsh.
[[ ! -f ~/.config/zsh/.p10k.zsh ]] || source ~/.config/zsh/.p10k.zsh

#zprof